from __future__ import annotations

from typing import Any
from uuid import uuid4

from verl.interactions.base import BaseInteraction


class SelfPlayUserInteraction(BaseInteraction):
    """Marker interaction for SimRec self-play rollouts.

    The actual user turns are generated inside the self-play agent loop by the
    same rollout model used for recommender turns. This class exists only so
    verl's multi-turn config path can pass per-sample interaction_kwargs into
    the agent loop without constructing an API-backed user simulator.
    """

    def __init__(self, config: dict[str, Any]):
        super().__init__(config)
        self._instance_dict: dict[str, dict[str, Any]] = {}

    async def start_interaction(self, instance_id: str | None = None, **kwargs) -> str:
        if instance_id is None:
            instance_id = str(uuid4())
        self._instance_dict[instance_id] = dict(kwargs)
        return instance_id

    async def generate_response(self, *args, **kwargs):
        raise RuntimeError("SimRec self-play user turns are generated by the self-play agent loop, not by an interaction API.")

    async def finalize_interaction(self) -> None:
        self._instance_dict.clear()
